# -*- coding: utf-8 -*-
"""Panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvBrFLGCh5BQI3igR1AWMBOuYT3Os2h8
"""

```python
def hitung_total_berat(daftar_berat):
    return sum(daftar_berat)


def hitung_total_harga(total_berat, harga_per_kg):
    return total_berat * harga_per_kg


def hitung_harga_akhir(total_harga, persen_diskon):
    if persen_diskon > 0:
        diskon = total_harga * persen_diskon / 100
        return total_harga - diskon
    else:
        return total_harga


# Data hasil panen
daftar_berat = [10, 15, 20, 12, 18]  # kg
harga_per_kg = 12000
persen_diskon = 10

# Perhitungan
total_berat = hitung_total_berat(daftar_berat)
total_harga = hitung_total_harga(total_berat, harga_per_kg)
harga_akhir = hitung_harga_akhir(total_harga, persen_diskon)

# Menampilkan hasil
print("Daftar berat:", daftar_berat, "kg")
print("Harga per kg: Rp", harga_per_kg)
print("Persen diskon:", persen_diskon, "%")
print("Total berat:", total_berat, "kg")
print("Total harga: Rp", total_harga)
print("Harga akhir: Rp", harga_akhir)
```